# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: CI/CD with GitHub Actions

on:
  push:
    branches: ["master", "dev"]
    paths:
      - "front/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Checkout Organization Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          repository: JobCatcher/recommend-lunch-menu # Organization의 원본 레포

      - name: Configure Git for Syncing Fork
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Debug GitHub Token
        run: |
          echo "Checking if PAT is available..."
          echo "Token length: ${{secrets.PERSONAL_ACCESS_TOKEN}}"

      - name: Add Fork Repository as Remote (via SSH)
        run: |
          git remote rename origin upstream
          git remote add origin git@github.com:lecto17/recommend-lunch-menu.git
          git fetch origin

      - name: Push to Fork
        run: |
          git checkout -B dev upstream/dev
          git remote -v
          git push origin dev --force

      - name: Checkout Fork Repository
        uses: actions/checkout@v4
        with:
          repository: lecto17/recommend-lunch-menu # 개인적으로 fork한 레포
          ref: dev
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Deploy to Vercel
        run: vercel --yes --prod --token=${{ secrets.VERCEL_TOKEN }}
